defaults:
  - models: GeoVisGNN # GeoVisGNN
  - data: mphoi72 # mphoi72, mphoi120, cad120, bimanual
hydra:
  run:
    dir: outputs/${data.name}/${metadata.model_name}/${logging.checkpoint_name}
resources:
  use_gpu: true
  num_threads: 32